language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - NODEJS_VERSION=6.10.3

before_script:
  - dpkg -l
  - cp .env.example .env
  - composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - cat .env
  - nvm install $NODEJS_VERSION
  - npm install
  - bower install
  - npm run dev
  - ls -la

script:
  - vendor/bin/phpunit
