version: '2'
services:
  netlicensing-demo:
    build: ./dockerfiles
    container_name: netlicensing-demo
    volumes:
      - ".:/var/www/netlicensing-demo"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - netlicensing-demo
    volumes:
      - ".:/var/www/netlicensing-demo"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: always
